@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

TaskWise *-right-> "1" UniqueTaskList
TaskWise *-right-> "1" UniqueMemberList
UniqueMemberList -[hidden]down- UniqueTaskList
UniqueMemberList -[hidden]down- UniqueTaskList

UniqueMemberList -right-> "*" Member
UniqueTaskList -right-> "~* all" Task

Task *-up-> "*" Member

Task *--> "1" Description
Task *--> "0..1" Deadline
Task *--> "0..1"Priority
Task *--> "0..1" Note
@enduml
