@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User enters mark command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

:Parse user input;

if () then ([command recognised])
    :Initialise MarkCommandParser object;
    :MarkCommandParser instance parses arguments;
    if () then ([parse successful])
        :Initialise MarkCommand instance;
        :LogicManager executes MarkCommand;
        if () then ([task is not already marked])
            :Update Status of Task to complete;
            :UI updates with new Task status;
            :Initialise CommandResult instance;
            :Return initialised CommandResult instance;
            :LogicManager parses CommandResult instance;
            :Display result to user;
        else ([else])
            :Display error message;
        endif
    else ([else])
        :Display error message;
    endif
else ([else])
:Display error message;
endif
stop

@enduml
