@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model as ModelPackage <<Rectangle>>{
Class "<<interface>>\nReadOnlyTaskWise" as ReadOnlyTaskWise
Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class "<<interface>>\nModel" as Model
Class TaskWise
Class ModelManager
Class UserPrefs

Class UniqueTaskList
Class Task
Class Note
Class Priority
Class Description
Class Deadline
Class Member

Class I #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

TaskWise .up.|> ReadOnlyTaskWise

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyTaskWise
ModelManager -left-> "1" TaskWise
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

TaskWise *--> "1" UniqueTaskList
UniqueTaskList ----> "~* all" Task
Task *--> "1" Description
Task *--> "0..1" Deadline
Task *--> "0..1" Priority
Task *--> "0..1" Note
Task *--> "*" Member

Task -[hidden]up--> I
UniqueTaskList -[hidden]right-> I

Description -[hidden]right-> Deadline
Deadline -[hidden]right-> Note
Note -[hidden]right-> Priority

ModelManager --> "~* filtered" Task
@enduml
