@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":TaskWiseParser" as TaskWiseParser LOGIC_COLOR
participant ":NoteCommandParser" as NoteCommandParser LOGIC_COLOR
participant "n:NoteCommand" as NoteCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":TaskWise" as TaskWise MODEL_COLOR
end box
[-> LogicManager : execute("note 1 n/note")
activate LogicManager

LogicManager -> TaskWiseParser : parseCommand("note 1 n/note")
activate TaskWiseParser

create NoteCommandParser
TaskWiseParser -> NoteCommandParser
activate NoteCommandParser

NoteCommandParser -> TaskWiseParser
deactivate NoteCommandParser

TaskWiseParser -> NoteCommandParser : parse("1 n/note")
activate NoteCommandParser

create NoteCommand
NoteCommandParser -> NoteCommand
activate NoteCommand

NoteCommand -> NoteCommandParser : n
deactivate NoteCommand

NoteCommandParser --> TaskWiseParser : n
deactivate NoteCommandParser

NoteCommandParser -[hidden]-> TaskWiseParser
destroy NoteCommandParser

TaskWiseParser --> LogicManager : n
deactivate TaskWiseParser

LogicManager -> NoteCommand : execute()
activate NoteCommand

NoteCommand -> Model : setTask(target, editedTask)
activate Model

Model -> TaskWise : setTask(target, editedTask)
activate TaskWise

TaskWise --> Model :
deactivate TaskWise

Model --> NoteCommand
deactivate Model

NoteCommand --> LogicManager : result
deactivate NoteCommand

[<--LogicManager
deactivate LogicManager
@enduml
