@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User enters unmark command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

:Parse user input;

if () then ([command recognised])
    :Initialise UnmarkCommandParser object;
    :UnmarkCommandParser instance parses arguments;
    if () then ([parse successful])
        :Initialise UnmarkCommand instance;
        :LogicManager executes UnmarkCommand;
        if () then ([task is not already unmarked])
            :Update Status of Task to incomplete;
            :UI updated with new Task status;
            :Initialise CommandResult instance;
            :Return initialised CommandResult instance;
            :LogicManager parses CommandResult instance;
            :Displays result to user;
        else ([else])
            :Display already unmarked error message;
        endif
    else ([else])
        :Display error message;
    endif
else ([else])
:Display error message;
endif
stop

@enduml
