@startuml
package commands.exceptions;{
    class CommandException
    class DuplicatedTaskException
    class IllegalCommandException
    class IllegalTaskIndexException

    DuplicatedTaskException -up-|> CommandException
    IllegalCommandException -up-|> CommandException
    IllegalTaskIndexException -up-|> IllegalCommandException

    hide members
}
@enduml
